# fly.toml app configuration file generated for puppeteer-service-dqpthw on 2025-10-02T18:16:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'puppeteer-service-dqpthw'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
